deltagreen-foundryvtt/delta-green-foundry-vtt-system

templates/item/item-weapon-sheet.html
Localization correction proposal to let the different translation be effective on FoundryVTT (isLethality)
=> [DeltaGreen system - FoundryVTT] Update item-weapon-sheet.html

css/deltagreen.css, lang/en.json, module/actor/actor-sheet.js, module/settings.js, templates/actor/actor-sheet.html
Add working skill improvement button;
Dialog allows multiple dice formula;
Global setting for default dice formula;
Localization;
=> Draft: Add skill improvement button

module/actor/actor-sheet.js
Skill improvements now work correctly for typed skills. The roll formula is now only chosen by GMs, which can be changed in the settings.
=> Skill Improvement Fixes

css/deltagreen.css, module/actor/actor-sheet.js, templates/actor/actor-sheet.html
=> Toggle lethality option from character sheet

module/deltagreen.js
**Issue**: 
When importing actors from the compendium or duplicating them, the default Typed Skill was erroneously being reverted back to Art (Painting), regardless of how the actor was configured. In the code, this was because we were using the `createActor` hook to translate this default skill. Unfortunately, this hook gets called for imported actors and duplicated actors alike, which called this translation code, which reverted this Typed Skill back to Art (Painting). So, we needed a solution that could identify when an actor was being imported/duped vs. being created brand new. The `preCreateActor` hook has an extra argument which provides the `creationData` for the actor. In a brand new actor, the only `creationData` are the properties `name` and `type`. In a duped/imported actor, …
=> Fix: Importing/Duplicating actors no longer resets default Typed Skill back to Art (Painting)

lang/ca.json, lang/en.json, lang/es.json, lang/ja.json, lang/pt-BR.json
=> Typo: Disdorder -> Disorder

module/actor/actor-sheet.js, templates/actor/custom-skills-partial.html
=> [ENH] Show target number for Special Trainings on the character sheet

css/deltagreen.css
=> "Handler only" Ritual description isn't shown correctly

CHANGELOG.md, lang/ca.json, lang/de.json, lang/en.json, lang/es.json, lang/fr.json, lang/ja.json, lang/pt-BR.json, lang/sv.json, template.json, templates/item/item-ritual-sheet.html
=> Ritual SAN Loss

css/deltagreen.css
=> UI Request: Delta Green Color Theming and Logo Alteration

module/actor/actor-sheet.js, module/actor/actor.js, module/settings.js, templates/actor/actor-sheet.html, templates/actor/npc-sheet.html, templates/actor/unnatural-sheet.html
=> [ENH] Skills sort by Language

README.md, css/deltagreen.css, module/actor/actor-sheet.js, templates/actor/actor-sheet.html, templates/actor/npc-sheet.html, templates/actor/partials/custom-skills-partial.html
=> [ENH] Sort Custom Skills & Special Trainings alphabetically / by column

css/deltagreen.css, module/actor/actor-sheet.js
=> Issue on last commit

lang/fr.json
Update Expense category FR localisation
=> Update Expense category FR localisation

css/deltagreen.css, module/actor/actor.js, module/roll/roll.js, templates/actor/actor-sheet.html
field need for support future effects
=> add calculated target proficiency

css/deltagreen.css, lang/ca.json, lang/cn.json, lang/de.json, lang/en.json, lang/es.json, lang/fr.json, lang/ja.json, lang/pl.json, lang/pt-BR.json, lang/sv.json, module/deltagreen.js, module/other/inline.js, module/other/utility-functions.js, module/roll/roll.js, templates/roll/percentile-roll.hbs
Feature add possibility to auto add failure checkbox when on failure roll but only if it's still not failure
post message to chat with new btn to undo/redo checkbox
=> add marker skill feature

css/dialogue.css, lang/en.json, module/other/stat-parser-macro.js, module/roll/roll.js, module/sheets/agent-sheet.js, module/sheets/base-actor-sheet.js, templates/dialog/modify-percentile-roll.html
=> use DialogV2 for SkillImprovements

system.json
Fixed https://github.com/TheLastScrub/delta-green-foundry-vtt-system/issues/229
=> delete deprecated keys

.editorconfig, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .github/actions/setup-node/action.yml, .github/workflows/format-lint-check.yml, .prettierignore, .vscode/extensions.json, CONTRIBUTING.md, css/dialogue.css, module/actor/actor.js, module/item/item-sheet.js, module/item/item.js, module/other/inline.js, module/other/macro-functions.js, module/other/stat-parser-macro.js, module/roll/roll.js, module/settings.js, package-lock.json, package.json, system.json
This PR does the following the following:
- Adds instructions for contributions:
- Tooling
- Setting up a development environment
- Git branching, commit, and PR standards
- Localization
- Fixes formatting and linting errors. There are still several warnings, but most of these are fine.
- Adds suggested extensions and settings for VSCode.
- Adds Github Actions for Pull Requests to make sure they pass linting/formatting checks.
=> Formatting, Linting, Contributing, etc.

.github/workflows/check-changelog.yml, CHANGELOG.md
This adds a test on PRs to make sure that CHANGELOG.md has been updated. Note, this check only runs if the PR has the `bug` or `enhancement` label. I have made a `bug dev` label for bugs that are not in a release, which will indicate to the test that it does not need to be run.
Note: The label `bug` on this PR is for testing purposes, it doesn't actually fix a bug.
1. Check that the changelog test here passes
=> Add changelog test

README.md, package.json, system.json, templates/actor/parts/about-tab.html
Removes references to the old repo and updates them with the new url.
1. Look at the changes and double-check that the changed links resolve correctly.
=> Update references to old repo

CONTRIBUTING.md, system.json
1. Change the `version` property in `system.json` to `dev`. This value gets updated automatically on release, and so I think it's confusing when this field has a version number in our master branch, since that isn't representative of the release. For example, prior to this PR, it was `version: v1.3.5`, which is untrue. Making this value `dev` makes it clear that the `master` branch represents our dev branch, distinct  
2. Fixes some formatting for code blocks in `CONTRIBUTING.md`
1. Nothing really to do for the `system.json` change
2. Look at `CONTRIBUTING.md` and make sure it looks right.
=> Small dev fixes

CHANGELOG.md, templates/item/item-armor-sheet.html, templates/item/item-bond-sheet.html, templates/item/item-gear-sheet.html, templates/item/item-motivation-sheet.html, templates/item/item-ritual-sheet.html, templates/item/item-tome-sheet.html
Fix possibility to edit bond description
1. Open Bond window
2. Edit description
3. Save it
3. Reopen and check that information is saved
Closes #263
=> fix 263 - edit bond

CHANGELOG.md, module/settings.js
Closed setting menu windows on save btn
1. Open Automation Setting Menu
2. Change checkbox 
3. Press Save
4. Window should closed
5. Reopen menu to check that setting was applied
6. Repeat logic with Handler menu
Closes #253
=> Fix(#253) Close setting windows on submit
